spring:
  application:
    name: carrito-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3301/electrodomesticos_carritos?useSSL=false&serverTimezone=UTC
    username: root
    password: ""

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
